apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpine
    version: v1
  name: alpine-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
      version: v1
  template:
    metadata:
      labels:
        app: alpine
        version: v1
    spec:
      containers:
      - image: alpine:latest
        name: alpine
        command: ["sleep", "8640000"]
---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: alpine
#  name: alpine
#spec:
#  ports:
#  - name: http
#    port: 80
#    protocol: TCP
#    targetPort: 80
#  selector:
#    app: alpine
#  type: ClusterIP
