---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: stdin
   
    output.file:
      path: "/tmp/input-save.log"
      filename: "input-svae.log"
